import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";


const migraFont = localFont({
  src: "../../public/._Migra-Extralight.woff2",
  variable: "--migra-font",
});

const inter = Inter({ subsets: ["latin"], variable: "--inter-font" });

export const metadata: Metadata = {
  title: "Data app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} bg-no-repeat font-sans ${migraFont.variable}`}>
        {children}
      </body>
    </html>
  );
}
